services:
  builder:
    platform: linux/amd64

    build:
      context: ../..
      dockerfile: .ci/module-build/Dockerfile
      platforms:
        - linux/amd64

    volumes:
      - ../../.skyfire/SkyFire_548:/workspace/skyfire
      - skyfire-ccache:/cache/ccache

volumes:
  skyfire-ccache:
